name = "spotirfid-worker"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[[kv_namespaces]]
binding = "READER_CONFIG"
id = "0cf5aa0da26f4715bbe5db62d5548ec0"

[[kv_namespaces]]
binding = "TOKEN_CACHE"
id = "a7e1b10df8894a49b937faa37532ef2f"

[env.production]
vars = { }

# Set these via: wrangler secret put <NAME>
# Required secrets:
# - SPOTIFY_CLIENT_ID
# - SPOTIFY_CLIENT_SECRET
